resources:
  - name: my_key
    type: integration
    integration: my_key
    
jobs:
  - name: test_pem
    type: runSh
    steps:
      - IN: my_key
      - TASK:
          script:
            - shipctl get_integration_resource_field my_key "key"
            - export KEY=$(shipctl get_integration_resource_field my_key "key")
            - echo -e "$KEY" > /tmp/key.pem
            - cat /tmp/key.pem
            - cp $MY_KEY_KEYPATH /tmp/my_key.pem
            - cat /tmp/my_key.pem
